name := "small_project_scalatest"
version := "0.1"
scalaVersion := "2.12.4"
resolvers += "Artima Maven Repository" at "https://repo.artima.com/releases"
libraryDependencies += "org.scalatest" %% "scalatest" % "3.0.4" % "test"